changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - .yarn/**/*

compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

enableProgressBars: false

nodeLinker: node-modules

npmPublishRegistry: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.11.0.cjs
