{
 "title": "Subql Node Dashboard",
 "description": "subql node prometheus metrics",
 "tags": [ "subql" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(subql_indexer_best_block_height, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Indexing Detail",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "subql_indexer_target_block_height{instance=~\"$instance\"}",
     "legendFormat": "Finalized Height - {{instance}} "
    },
    {
     "expr": "subql_indexer_best_block_height{instance=~\"$instance\"}",
     "legendFormat": "Best Height - {{instance}} "
    },
    {
     "expr": "subql_indexer_processing_block_height{instance=~\"$instance\"}",
     "legendFormat": "Processing Height - {{instance}} "
    },
    {
     "expr": "subql_indexer_processed_block_count{instance=~\"$instance\"}",
     "legendFormat": "Processed Height - {{instance}} "
    }
   ]
  },
  {
   "title": "Processing Queue Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "subql_indexer_block_queue_size{instance=~\"$instance\"}",
     "legendFormat": "Queue Size - {{instance}} "
    }
   ]
  },
  {
   "title": "Block Number Queue Size ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "subql_indexer_blocknumber_queue_size{instance=~\"$instance\"}",
     "legendFormat": "Block Number Queue Size - {{instance}} "
    }
   ]
  },
  {
   "title": "Store Cache Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "subql_indexer_store_cache_threshold{instance=~\"$instance\"}",
     "legendFormat": "Cache Threshold - {{instance}} "
    },
    {
     "expr": "subql_indexer_store_cache_records_size{instance=~\"$instance\"}",
     "legendFormat": "Cache Records Size - {{instance}} "
    }
   ]
  },
  {
   "title": "Connection Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "subql_indexer_api_connected{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Skip Dictionary Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "subql_indexer_skip_dictionary_count{instance=~\"$instance\"}",
     "legendFormat": "Skip Count - {{instance}} "
    }
   ]
  },
  {
   "title": "Using the dictionary",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "subql_indexer_using_dictionary{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}