version: '3.5'

services:
  crdb:
    image: cockroachdb/cockroach:latest-v22.1
    ports:
      - '26257:26257'
      - '8080:8080'
    command: start-single-node --insecure
    volumes:
      - '${PWD}/cockroach-data/crdb:/cockroach/cockroach-data'
