// Copyright 2020-2025 SubQuery Pte Ltd authors & contributors
// SPDX-License-Identifier: GPL-3.0

import {createTestContext} from './testHelpers';

jest.mock('../../../yargs', () => {
  const getYargsOption = jest.fn(() => ({
    argv: {
      name: 'test',
      aggregate: true,
      'query-limit': 100,
      unsafe: false,
      'order-by-nulls-last': undefined,
      indexer: undefined,
    },
  }));
  const argv = (arg) => getYargsOption().argv[arg];
  return {
    getYargsOption,
    argv,
  };
});

describe('PgAggregationPlugin (PgAggregatesPreset + PgAggregateTextCastPlugin)', () => {
  const dbSchema = 'subquery_aggregation_test';
  const {pool, runQuery} = createTestContext(dbSchema);

  beforeAll(async () => {
    await pool.query(`CREATE SCHEMA IF NOT EXISTS "${dbSchema}"`);

    // Table with various numeric columns + _id for smart tag testing
    await pool.query(`
      CREATE TABLE IF NOT EXISTS "${dbSchema}".agg_item (
        id SERIAL PRIMARY KEY,
        category TEXT,
        value INTEGER,
        big_value BIGINT,
        _id TEXT,
        _block_range INT8RANGE
      )
    `);

    await pool.query(`
      INSERT INTO "${dbSchema}".agg_item (category, value, big_value, _id, _block_range) VALUES
        ('a', 10, 1000000000000001, 'id_1', '[,]'::int8range),
        ('a', 20, 1000000000000002, 'id_2', '[,]'::int8range),
        ('b', 30, 1000000000000003, 'id_3', '[,]'::int8range)
    `);
  });

  afterAll(async () => {
    await pool.query(`DROP SCHEMA IF EXISTS "${dbSchema}" CASCADE`);
    await pool.end();
  });

  it('returns correct sum/min/max for integer column', async () => {
    // Note: avg not generated by default pgAggregateSpecs, only sum/min/max/count
    // sum has sqlAggregateWrap (coalesce) so ::text applies → string
    // min/max have no sqlAggregateWrap → native type (number)
    const result = await runQuery(`
      { aggItems { aggregates { sum { value } min { value } max { value } } } }
    `);
    expect(result.errors).toBeUndefined();
    const aggs = result.data?.aggItems?.aggregates;
    expect(aggs).toBeDefined();
    expect(aggs.sum.value).toBe('60'); // ::text via coalesce wrap
    expect(aggs.min.value).toBe(10); // native integer
    expect(aggs.max.value).toBe(30); // native integer
  });

  it('returns bigint aggregate values as strings (precision preservation)', async () => {
    // Note: avg is not generated for BIGINT columns by default specs
    const result = await runQuery(`
      { aggItems { aggregates { sum { bigValue } min { bigValue } max { bigValue } } } }
    `);
    expect(result.errors).toBeUndefined();
    const aggs = result.data?.aggItems?.aggregates;
    expect(aggs).toBeDefined();
    // bigValue values must be strings (BigInt scalar + ::text)
    expect(typeof aggs.sum.bigValue).toBe('string');
    expect(typeof aggs.min.bigValue).toBe('string');
    expect(typeof aggs.max.bigValue).toBe('string');
    // sum = 1000000000000001 + 1000000000000002 + 1000000000000003 = 3000000000000006
    expect(aggs.sum.bigValue).toBe('3000000000000006');
  });

  it('excludes _id from aggregate orderBy enum (pgSmartTags behavior)', async () => {
    const result = await runQuery(`
      { __type(name: "AggItemOrderBy") { enumValues { name } } }
    `);
    expect(result.errors).toBeUndefined();
    const names = result.data?.__type?.enumValues?.map((v: any) => v.name) || [];
    // _id should be excluded by behavior -attribute:aggregate:orderBy
    expect(names).not.toContain('_ID');
    expect(names).not.toContain('ID');
  });

  it('aggregate queries work with category grouping', async () => {
    // groupedAggregates returns a list of AggItemGroupedAggregate with keys + agg fields directly
    const result = await runQuery(`
      {
        aggItems {
          groupedAggregates(groupBy: CATEGORY) {
            keys
            sum { value }
            min { value }
            max { value }
          }
        }
      }
    `);
    expect(result.errors).toBeUndefined();
    const groups = result.data?.aggItems?.groupedAggregates || [];
    expect(groups).toHaveLength(2);
    const catA = groups.find((g: any) => g.keys?.[0] === 'a');
    const catB = groups.find((g: any) => g.keys?.[0] === 'b');
    expect(catA).toBeDefined();
    expect(catB).toBeDefined();
    // category 'a': value 10+20 = 30
    expect(catA.sum.value).toBe('30');
    // category 'b': value 30
    expect(catB.sum.value).toBe('30');
  });
});
